import { fieldsProxy } from "@serenity-is/corelib";

export interface Pfk7411Row {
    Idno?: string;
    DevelopmenetCode?: string;
    IdCard?: string;
    IdhrCode?: string;
    UserId?: string;
    PassWord?: string;
    Name?: string;
    ForeignName?: string;
    SeSite?: string;
    CdSite?: string;
    SeMainProcess?: string;
    CdMainProcess?: string;
    SeSubProcess?: string;
    CdSubProcess?: string;
    SeNationality?: string;
    CdNationality?: string;
    SeDepartment?: string;
    CdDepartment?: string;
    SeOnePosition?: string;
    CdOnePosition?: string;
    SePosition?: string;
    CdPosition?: string;
    SeInCharge?: string;
    CdInCharge?: string;
    SeFactory?: string;
    CdFactory?: string;
    SeLineProd?: string;
    CdLineProd?: string;
    Email?: string;
    Mobile?: string;
    Gender?: string;
    SendEmail?: string;
    SendSms?: string;
    SendFax?: string;
    Locked?: string;
    OpenCdt?: string;
    OpenPrvDays?: string;
    OpenRate?: string;
    OpenSchedule?: string;
    OpenAlert?: string;
    OpenMessage?: string;
    ScreenLock?: number;
    Idcd?: string;
    Dgcd?: string;
    Gnid?: string;
    DateInsert?: string;
    DateUpdate?: string;
    InchargeInsert?: string;
    InchargeUpdate?: string;
    DateActive?: string;
    DateDeactive?: string;
    CheckActive?: string;
    FirstChangePass?: string;
    LastPass?: string;
    LastPass1?: string;
    LastPass2?: string;
    FailLoginCnt?: number;
    CheckNever?: string;
    LastLogin?: string;
    LastTime?: string;
    CheckOption1?: string;
    CheckOption2?: string;
    CheckOption3?: string;
    CheckOption4?: string;
    CheckOption5?: string;
    CheckUse?: string;
    DepName?: string;
    EmpTypeName?: string;
    PosName?: string;
    LineName?: string;
    TeamName?: string;
    PartName?: string;
    CheckDev?: string;
}

export abstract class Pfk7411Row {
    static readonly idProperty = 'Idno';
    static readonly nameProperty = 'Idno';
    static readonly localTextPrefix = 'Default.Pfk7411';
    static readonly deletePermission = 'Administration:General';
    static readonly insertPermission = 'Administration:General';
    static readonly readPermission = 'Administration:General';
    static readonly updatePermission = 'Administration:General';

    static readonly Fields = fieldsProxy<Pfk7411Row>();
}