using Serenity.ComponentModel;
using System.ComponentModel;

namespace SerenePSM.Default.Columns;

[ColumnsScript("Default.Pfk7106")]
[BasedOnRow(typeof(Pfk7106Row), CheckNames = true)]
public class Pfk7106Columns
{
    [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
    public string ShoesCode { get; set; }
    public string ShoesCodeBase { get; set; }
    public string Customercode { get; set; }
    public string BackColor { get; set; }
    public string CustSpecNo { get; set; }
    public string ProductCode { get; set; }
    public string Style { get; set; }
    public string Article { get; set; }
    public string Line { get; set; }
    public string Mcode { get; set; }
    public string ColorCode { get; set; }
    public string McodeName { get; set; }
    public string ColorName { get; set; }
    public string VerAll { get; set; }
    public string VerSam { get; set; }
    public string VerBom { get; set; }
    public string VerCbd { get; set; }
    public string VerRot { get; set; }
    public string VerJob { get; set; }
    public string CustSpecNo1 { get; set; }
    public string SeProductType { get; set; }
    public string CdProductType { get; set; }
    public string SeProductSize { get; set; }
    public string CdProductSize { get; set; }
    public string SeSpecState { get; set; }
    public string CdSpecState { get; set; }
    public string Szno { get; set; }
    public string SpeciticSize { get; set; }
    public string SeSeason { get; set; }
    public string CdSeason { get; set; }
    public string SeGender { get; set; }
    public string CdGender { get; set; }
    public string LastCode { get; set; }
    public string LastWidth { get; set; }
    public decimal LastQty { get; set; }
    public string MoldCode { get; set; }
    public string MoldSpec { get; set; }
    public decimal MoldQty { get; set; }
    public decimal QtyAverage { get; set; }
    public decimal QtyAverage1 { get; set; }
    public decimal QtyAverage2 { get; set; }
    public decimal QtyAverage3 { get; set; }
    public string CuttingDieCode { get; set; }
    public string TexonCode { get; set; }
    public string TexonColor { get; set; }
    public string InsoleCode { get; set; }
    public string InsoleColor { get; set; }
    public string OutsoleCode { get; set; }
    public string OutsoleColor { get; set; }
    public string OutsoleColorCode { get; set; }
    public string MidSoleCode { get; set; }
    public string MidsoleColor { get; set; }
    public string LogoCode { get; set; }
    public string LogoColor { get; set; }
    public string LogoColorCode { get; set; }
    public string SizeRange { get; set; }
    public string Note0 { get; set; }
    public string Note1 { get; set; }
    public string Note2 { get; set; }
    public string Note3 { get; set; }
    public string Note4 { get; set; }
    public string Note5 { get; set; }
    public string Note6 { get; set; }
    public string Note7 { get; set; }
    public string Note8 { get; set; }
    public string Note9 { get; set; }
    public string Note10 { get; set; }
    public string DateExchangePrice { get; set; }
    public decimal ExchangePrice { get; set; }
    public decimal PriceUsd { get; set; }
    public decimal PriceVnd { get; set; }
    public string DateLable1 { get; set; }
    public string DateLable2 { get; set; }
    public string DateLable3 { get; set; }
    public string DateInsert { get; set; }
    public string DateUpdate { get; set; }
    public string InchargeDesigner { get; set; }
    public string InchargeStep1 { get; set; }
    public string InchargeStep2 { get; set; }
    public string InchargeStep3 { get; set; }
    public string InchargeInsert { get; set; }
    public string InchargeUpdate { get; set; }
    public string InchargeCbdI { get; set; }
    public string InchargeCbdU { get; set; }
    public string InchargeBomI { get; set; }
    public string InchargeBomU { get; set; }
    public string InchargeConI { get; set; }
    public string InchargeConU { get; set; }
    public string CheckParent { get; set; }
    public string ShoesParent { get; set; }
    public string CheckUse { get; set; }
    public string TimeInsert { get; set; }
    public string TimeUpdate { get; set; }
    public string CheckComplete { get; set; }
    public string InchargeComplete { get; set; }
    public string DateComplete { get; set; }
    public string InchargeCompleteUn { get; set; }
    public string DateCompleteUn { get; set; }
    public string TimeComplete { get; set; }
    public string CheckBom { get; set; }
    public string InchargeBomCom { get; set; }
    public string DateBomCom { get; set; }
    public string InchargeBomUn { get; set; }
    public string DateBomUn { get; set; }
    public string TimeBomCom { get; set; }
    public string CheckCbd { get; set; }
    public string InchargeCbdCom { get; set; }
    public string DateCbdCom { get; set; }
    public string InchargeCbdUn { get; set; }
    public string DateCbdUn { get; set; }
    public string TimeCbdCom { get; set; }
    public string CheckCon { get; set; }
    public string InchargeConCom { get; set; }
    public string DateConCom { get; set; }
    public string InchargeConUn { get; set; }
    public string DateConUn { get; set; }
    public string TimeConCom { get; set; }
    public string CheckFb { get; set; }
    public string CheckSameMold { get; set; }
    public string Remark { get; set; }
    public string SeSite { get; set; }
    public string CdSite { get; set; }
}