import { StringEditor, DecimalEditor, PrefixedContext, initFormType } from "@serenity-is/corelib";

export interface Pfk7101Form {
    QrCode: StringEditor;
    ACodeReceivable: StringEditor;
    ACodePayable: StringEditor;
    DevelopmentCode: StringEditor;
    QrCodeName: StringEditor;
    QrCodeTel: StringEditor;
    CustomerName: StringEditor;
    CustomerName1: StringEditor;
    CustomerNameSimply: StringEditor;
    CustomerNameSimply1: StringEditor;
    FaceId: StringEditor;
    SePassWord: StringEditor;
    CdPassWord: StringEditor;
    SeDeliveryTerm: StringEditor;
    CdDeliveryTerm: StringEditor;
    SePaymentTerm: StringEditor;
    CdPaymentTerm: StringEditor;
    SePaymentCondition: StringEditor;
    CdPaymentCondition: StringEditor;
    SePaymentDay: StringEditor;
    CdPaymentDay: StringEditor;
    SePaymentTime: StringEditor;
    CdPaymentTime: StringEditor;
    SeSite: StringEditor;
    CdSite: StringEditor;
    SeTeam: StringEditor;
    CdTeam: StringEditor;
    ForeignName1: StringEditor;
    ForeignName2: StringEditor;
    CompanyId: StringEditor;
    CompanyType: StringEditor;
    CompanyItem: StringEditor;
    Representative: StringEditor;
    AddressNo: StringEditor;
    Address1: StringEditor;
    Address2: StringEditor;
    Destination: StringEditor;
    FinalShop: StringEditor;
    Country: StringEditor;
    InvoiceAccount: StringEditor;
    TaxExempt: StringEditor;
    SeSupplierGroup: StringEditor;
    CdSupplierGroup: StringEditor;
    SePoGroup: StringEditor;
    CdPoGroup: StringEditor;
    SeSoGroup: StringEditor;
    CdSoGroup: StringEditor;
    TelephoneCompany: StringEditor;
    TelephoneHand: StringEditor;
    FaxNo: StringEditor;
    Email: StringEditor;
    BeneficiaryName: StringEditor;
    AccountNumber: StringEditor;
    BankName: StringEditor;
    BankAddress: StringEditor;
    SwiftCode: StringEditor;
    CdFactory: StringEditor;
    CheckKindCustomer: StringEditor;
    SeCancelDate: StringEditor;
    CdCancelDate: StringEditor;
    SeCustomerDivision: StringEditor;
    CdCustomerDivision: StringEditor;
    SeCustomerLocation: StringEditor;
    CdCustomerLocation: StringEditor;
    SeTaxGroup: StringEditor;
    CdTaxGroup: StringEditor;
    InCharge: StringEditor;
    InChargeSale: StringEditor;
    CheckTax: StringEditor;
    CheckCustomer: StringEditor;
    CheckSupplier: StringEditor;
    CheckEmployee: StringEditor;
    CheckInside: StringEditor;
    CheckOutside: StringEditor;
    CheckOthers: StringEditor;
    CheckUse: StringEditor;
    InchargeInsert: StringEditor;
    InchargeUpdate: StringEditor;
    DateInsert: StringEditor;
    DateUpdate: StringEditor;
    TimeInsert: StringEditor;
    TimeUpdate: StringEditor;
    TimeLast: StringEditor;
    DateActive: StringEditor;
    DateDeactive: StringEditor;
    CheckActive: StringEditor;
    ParaNo1: DecimalEditor;
    ParaNo2: DecimalEditor;
    ParaNo3: DecimalEditor;
    CheckSync: StringEditor;
    CheckCustomerStatus: StringEditor;
    DateComplete: StringEditor;
    DateApproved: StringEditor;
    DateCancel: StringEditor;
    DatePending1: StringEditor;
    DatePending2: StringEditor;
    Remark: StringEditor;
    CheckOption1: StringEditor;
    CheckOption2: StringEditor;
    CheckOption3: StringEditor;
    CheckOption4: StringEditor;
    CheckOption5: StringEditor;
    CheckOption6: StringEditor;
    CheckOption7: StringEditor;
    CheckOption8: StringEditor;
    CheckOption9: StringEditor;
    CheckOption10: StringEditor;
    Shipper: StringEditor;
    ShipperTo: StringEditor;
    Buyer: StringEditor;
    Consignee: StringEditor;
    LcNo: StringEditor;
    DateLc: StringEditor;
    Notifyparty: StringEditor;
    NotifypartyAnd: StringEditor;
    VisAllName: StringEditor;
    DateDepart: StringEditor;
    FlightNo: StringEditor;
    ShipFrom: StringEditor;
    ShipTo: StringEditor;
    ShipMark: StringEditor;
    Remarks: StringEditor;
    TermPri: StringEditor;
    Shipper1: StringEditor;
    ShipperTo1: StringEditor;
    Buyer1: StringEditor;
    Consignee1: StringEditor;
    LcNo1: StringEditor;
    DateLc1: StringEditor;
    Notifyparty1: StringEditor;
    NotifypartyAnd1: StringEditor;
    VisAllName1: StringEditor;
    DateDepart1: StringEditor;
    FlightNo1: StringEditor;
    ShipFrom1: StringEditor;
    ShipTo1: StringEditor;
    ShipMark1: StringEditor;
    Remarks1: StringEditor;
    TermPri1: StringEditor;
}

export class Pfk7101Form extends PrefixedContext {
    static readonly formKey = 'Default.Pfk7101';
    private static init: boolean;

    constructor(prefix: string) {
        super(prefix);

        if (!Pfk7101Form.init)  {
            Pfk7101Form.init = true;

            var w0 = StringEditor;
            var w1 = DecimalEditor;

            initFormType(Pfk7101Form, [
                'QrCode', w0,
                'ACodeReceivable', w0,
                'ACodePayable', w0,
                'DevelopmentCode', w0,
                'QrCodeName', w0,
                'QrCodeTel', w0,
                'CustomerName', w0,
                'CustomerName1', w0,
                'CustomerNameSimply', w0,
                'CustomerNameSimply1', w0,
                'FaceId', w0,
                'SePassWord', w0,
                'CdPassWord', w0,
                'SeDeliveryTerm', w0,
                'CdDeliveryTerm', w0,
                'SePaymentTerm', w0,
                'CdPaymentTerm', w0,
                'SePaymentCondition', w0,
                'CdPaymentCondition', w0,
                'SePaymentDay', w0,
                'CdPaymentDay', w0,
                'SePaymentTime', w0,
                'CdPaymentTime', w0,
                'SeSite', w0,
                'CdSite', w0,
                'SeTeam', w0,
                'CdTeam', w0,
                'ForeignName1', w0,
                'ForeignName2', w0,
                'CompanyId', w0,
                'CompanyType', w0,
                'CompanyItem', w0,
                'Representative', w0,
                'AddressNo', w0,
                'Address1', w0,
                'Address2', w0,
                'Destination', w0,
                'FinalShop', w0,
                'Country', w0,
                'InvoiceAccount', w0,
                'TaxExempt', w0,
                'SeSupplierGroup', w0,
                'CdSupplierGroup', w0,
                'SePoGroup', w0,
                'CdPoGroup', w0,
                'SeSoGroup', w0,
                'CdSoGroup', w0,
                'TelephoneCompany', w0,
                'TelephoneHand', w0,
                'FaxNo', w0,
                'Email', w0,
                'BeneficiaryName', w0,
                'AccountNumber', w0,
                'BankName', w0,
                'BankAddress', w0,
                'SwiftCode', w0,
                'CdFactory', w0,
                'CheckKindCustomer', w0,
                'SeCancelDate', w0,
                'CdCancelDate', w0,
                'SeCustomerDivision', w0,
                'CdCustomerDivision', w0,
                'SeCustomerLocation', w0,
                'CdCustomerLocation', w0,
                'SeTaxGroup', w0,
                'CdTaxGroup', w0,
                'InCharge', w0,
                'InChargeSale', w0,
                'CheckTax', w0,
                'CheckCustomer', w0,
                'CheckSupplier', w0,
                'CheckEmployee', w0,
                'CheckInside', w0,
                'CheckOutside', w0,
                'CheckOthers', w0,
                'CheckUse', w0,
                'InchargeInsert', w0,
                'InchargeUpdate', w0,
                'DateInsert', w0,
                'DateUpdate', w0,
                'TimeInsert', w0,
                'TimeUpdate', w0,
                'TimeLast', w0,
                'DateActive', w0,
                'DateDeactive', w0,
                'CheckActive', w0,
                'ParaNo1', w1,
                'ParaNo2', w1,
                'ParaNo3', w1,
                'CheckSync', w0,
                'CheckCustomerStatus', w0,
                'DateComplete', w0,
                'DateApproved', w0,
                'DateCancel', w0,
                'DatePending1', w0,
                'DatePending2', w0,
                'Remark', w0,
                'CheckOption1', w0,
                'CheckOption2', w0,
                'CheckOption3', w0,
                'CheckOption4', w0,
                'CheckOption5', w0,
                'CheckOption6', w0,
                'CheckOption7', w0,
                'CheckOption8', w0,
                'CheckOption9', w0,
                'CheckOption10', w0,
                'Shipper', w0,
                'ShipperTo', w0,
                'Buyer', w0,
                'Consignee', w0,
                'LcNo', w0,
                'DateLc', w0,
                'Notifyparty', w0,
                'NotifypartyAnd', w0,
                'VisAllName', w0,
                'DateDepart', w0,
                'FlightNo', w0,
                'ShipFrom', w0,
                'ShipTo', w0,
                'ShipMark', w0,
                'Remarks', w0,
                'TermPri', w0,
                'Shipper1', w0,
                'ShipperTo1', w0,
                'Buyer1', w0,
                'Consignee1', w0,
                'LcNo1', w0,
                'DateLc1', w0,
                'Notifyparty1', w0,
                'NotifypartyAnd1', w0,
                'VisAllName1', w0,
                'DateDepart1', w0,
                'FlightNo1', w0,
                'ShipFrom1', w0,
                'ShipTo1', w0,
                'ShipMark1', w0,
                'Remarks1', w0,
                'TermPri1', w0
            ]);
        }
    }
}