import { StringEditor, DecimalEditor, BooleanEditor, PrefixedContext, initFormType } from "@serenity-is/corelib";

export interface Pfk7231Form {
    MaterialName: StringEditor;
    MaterialPName: StringEditor;
    MaterialSimple: StringEditor;
    MaterialColor: StringEditor;
    SeImportGroup: StringEditor;
    CdImportGroup: StringEditor;
    Hscode: StringEditor;
    LogisticCodeSg: StringEditor;
    ImportCode: StringEditor;
    ImportName: StringEditor;
    Hscode1: StringEditor;
    ImportCode1: StringEditor;
    ImportName1: StringEditor;
    AccountCode: StringEditor;
    AccountName: StringEditor;
    OtherCode1: StringEditor;
    OtherCode2: StringEditor;
    DevelopmentCode: StringEditor;
    DevelopmentName: StringEditor;
    MaterialForeign1: StringEditor;
    MaterialForeign2: StringEditor;
    Width: StringEditor;
    Height: StringEditor;
    SizeName: StringEditor;
    CheckPrint: StringEditor;
    CheckSp: StringEditor;
    SeSpecial: StringEditor;
    CdSpecial: StringEditor;
    SizeRangeTool: StringEditor;
    CheckKindMaterial: StringEditor;
    CheckMarketType: StringEditor;
    SeUnitPrice: StringEditor;
    CdUnitPrice: StringEditor;
    DateExchangePrice: StringEditor;
    ExchangePrice: DecimalEditor;
    PriceUsd: DecimalEditor;
    PriceVnd: DecimalEditor;
    SeDepartment: StringEditor;
    CdDepartment: StringEditor;
    SeLargeGroupMaterial: StringEditor;
    CdLargeGroupMaterial: StringEditor;
    SeSemiGroupMaterial: StringEditor;
    CdSemiGroupMaterial: StringEditor;
    SeDetailGroupMaterial: StringEditor;
    CdDetailGroupMaterial: StringEditor;
    SeSpecGroup1: StringEditor;
    CdSpecGroup1: StringEditor;
    SeSpecGroup2: StringEditor;
    CdSpecGroup2: StringEditor;
    SeSpecGroup3: StringEditor;
    CdSpecGroup3: StringEditor;
    SeSpecGroup4: StringEditor;
    CdSpecGroup4: StringEditor;
    SeSpecGroup5: StringEditor;
    CdSpecGroup5: StringEditor;
    SeUnitMaterial: StringEditor;
    CdUnitMaterial: StringEditor;
    SeUnitPacking: StringEditor;
    CdUnitPacking: StringEditor;
    SeTax: StringEditor;
    CdTax: StringEditor;
    PerTaxImport: DecimalEditor;
    PerTaxVat: DecimalEditor;
    QtyBasic: DecimalEditor;
    QtyOptimum: DecimalEditor;
    DayOptimum: DecimalEditor;
    DayEstimate: DecimalEditor;
    PriceMaterial: DecimalEditor;
    QtyMoq: DecimalEditor;
    MaxInventory: DecimalEditor;
    MinInventory: DecimalEditor;
    ReOrderQty: DecimalEditor;
    CheckDevRnD: StringEditor;
    StatusMaterial: StringEditor;
    BomType: StringEditor;
    ApplyType: StringEditor;
    DateStart: StringEditor;
    DateOptimum: StringEditor;
    DateEstimate: StringEditor;
    DateInBound: StringEditor;
    DateOutBound: StringEditor;
    SupplyName: StringEditor;
    SupplyCode: StringEditor;
    SalesCode: StringEditor;
    Check1: StringEditor;
    Check2: StringEditor;
    Check3: StringEditor;
    Check4: StringEditor;
    Check5: StringEditor;
    Check6: StringEditor;
    Check7: StringEditor;
    Check8: StringEditor;
    Check9: StringEditor;
    Check10: StringEditor;
    CheckName1: StringEditor;
    CheckName2: StringEditor;
    CheckName3: StringEditor;
    CheckName4: StringEditor;
    CheckName5: StringEditor;
    CheckName6: StringEditor;
    CheckName7: StringEditor;
    CheckName8: StringEditor;
    CheckName9: StringEditor;
    CheckName10: StringEditor;
    ACodeMaterial: StringEditor;
    ACodeTax1: StringEditor;
    ACodeTax2: StringEditor;
    ACodeTax3: StringEditor;
    ACodeSales: StringEditor;
    ACodeIntSales: StringEditor;
    ACodeCogs: StringEditor;
    ACodeReturn: StringEditor;
    ACodeDiscount: StringEditor;
    ACodeWip: StringEditor;
    CheckInventory: StringEditor;
    CheckPosition: StringEditor;
    CheckLotNo: StringEditor;
    CheckPrice: StringEditor;
    SeTax1: StringEditor;
    CdTax1: StringEditor;
    PerTax1: DecimalEditor;
    SeTax2: StringEditor;
    CdTax2: StringEditor;
    PerTax2: DecimalEditor;
    SeTax3: StringEditor;
    CdTax3: StringEditor;
    PerTax3: DecimalEditor;
    SeTaxVat: StringEditor;
    CdTaxVat: StringEditor;
    SeTaxImport: StringEditor;
    CdTaxImport: StringEditor;
    SeTaxExport: StringEditor;
    CdTaxExport: StringEditor;
    SeTaxSpecial: StringEditor;
    CdTaxSpecial: StringEditor;
    SeAccMaterial: StringEditor;
    CdAccMaterial: StringEditor;
    SeAccSales: StringEditor;
    CdAccSales: StringEditor;
    SeAccIntSales: StringEditor;
    CdAccIntSales: StringEditor;
    SeAccCogs: StringEditor;
    CdAccCogs: StringEditor;
    SeAccReturn: StringEditor;
    CdAccReturn: StringEditor;
    SeAccDiscount: StringEditor;
    CdAccDiscount: StringEditor;
    SeAccWip: StringEditor;
    CdAccWip: StringEditor;
    DateInsert: StringEditor;
    DateUpdate: StringEditor;
    InchargeInsert: StringEditor;
    InchargeUpdate: StringEditor;
    InchargeComplete: StringEditor;
    InchargeCancel: StringEditor;
    InchargeApproved: StringEditor;
    InchargePending1: StringEditor;
    InchargePending2: StringEditor;
    CheckUse: BooleanEditor;
    DateActive: StringEditor;
    DateDeactive: StringEditor;
    CheckActive: StringEditor;
    DateComplete: StringEditor;
    DateApproved: StringEditor;
    DateCancel: StringEditor;
    DatePending1: StringEditor;
    DatePending2: StringEditor;
    CheckSync: StringEditor;
    MaterialFullName: StringEditor;
    MaterialOldName: StringEditor;
    Remark: StringEditor;
    SeSite: StringEditor;
    CdSite: StringEditor;
}

export class Pfk7231Form extends PrefixedContext {
    static readonly formKey = 'Default.Pfk7231';
    private static init: boolean;

    constructor(prefix: string) {
        super(prefix);

        if (!Pfk7231Form.init)  {
            Pfk7231Form.init = true;

            var w0 = StringEditor;
            var w1 = DecimalEditor;
            var w2 = BooleanEditor;

            initFormType(Pfk7231Form, [
                'MaterialName', w0,
                'MaterialPName', w0,
                'MaterialSimple', w0,
                'MaterialColor', w0,
                'SeImportGroup', w0,
                'CdImportGroup', w0,
                'Hscode', w0,
                'LogisticCodeSg', w0,
                'ImportCode', w0,
                'ImportName', w0,
                'Hscode1', w0,
                'ImportCode1', w0,
                'ImportName1', w0,
                'AccountCode', w0,
                'AccountName', w0,
                'OtherCode1', w0,
                'OtherCode2', w0,
                'DevelopmentCode', w0,
                'DevelopmentName', w0,
                'MaterialForeign1', w0,
                'MaterialForeign2', w0,
                'Width', w0,
                'Height', w0,
                'SizeName', w0,
                'CheckPrint', w0,
                'CheckSp', w0,
                'SeSpecial', w0,
                'CdSpecial', w0,
                'SizeRangeTool', w0,
                'CheckKindMaterial', w0,
                'CheckMarketType', w0,
                'SeUnitPrice', w0,
                'CdUnitPrice', w0,
                'DateExchangePrice', w0,
                'ExchangePrice', w1,
                'PriceUsd', w1,
                'PriceVnd', w1,
                'SeDepartment', w0,
                'CdDepartment', w0,
                'SeLargeGroupMaterial', w0,
                'CdLargeGroupMaterial', w0,
                'SeSemiGroupMaterial', w0,
                'CdSemiGroupMaterial', w0,
                'SeDetailGroupMaterial', w0,
                'CdDetailGroupMaterial', w0,
                'SeSpecGroup1', w0,
                'CdSpecGroup1', w0,
                'SeSpecGroup2', w0,
                'CdSpecGroup2', w0,
                'SeSpecGroup3', w0,
                'CdSpecGroup3', w0,
                'SeSpecGroup4', w0,
                'CdSpecGroup4', w0,
                'SeSpecGroup5', w0,
                'CdSpecGroup5', w0,
                'SeUnitMaterial', w0,
                'CdUnitMaterial', w0,
                'SeUnitPacking', w0,
                'CdUnitPacking', w0,
                'SeTax', w0,
                'CdTax', w0,
                'PerTaxImport', w1,
                'PerTaxVat', w1,
                'QtyBasic', w1,
                'QtyOptimum', w1,
                'DayOptimum', w1,
                'DayEstimate', w1,
                'PriceMaterial', w1,
                'QtyMoq', w1,
                'MaxInventory', w1,
                'MinInventory', w1,
                'ReOrderQty', w1,
                'CheckDevRnD', w0,
                'StatusMaterial', w0,
                'BomType', w0,
                'ApplyType', w0,
                'DateStart', w0,
                'DateOptimum', w0,
                'DateEstimate', w0,
                'DateInBound', w0,
                'DateOutBound', w0,
                'SupplyName', w0,
                'SupplyCode', w0,
                'SalesCode', w0,
                'Check1', w0,
                'Check2', w0,
                'Check3', w0,
                'Check4', w0,
                'Check5', w0,
                'Check6', w0,
                'Check7', w0,
                'Check8', w0,
                'Check9', w0,
                'Check10', w0,
                'CheckName1', w0,
                'CheckName2', w0,
                'CheckName3', w0,
                'CheckName4', w0,
                'CheckName5', w0,
                'CheckName6', w0,
                'CheckName7', w0,
                'CheckName8', w0,
                'CheckName9', w0,
                'CheckName10', w0,
                'ACodeMaterial', w0,
                'ACodeTax1', w0,
                'ACodeTax2', w0,
                'ACodeTax3', w0,
                'ACodeSales', w0,
                'ACodeIntSales', w0,
                'ACodeCogs', w0,
                'ACodeReturn', w0,
                'ACodeDiscount', w0,
                'ACodeWip', w0,
                'CheckInventory', w0,
                'CheckPosition', w0,
                'CheckLotNo', w0,
                'CheckPrice', w0,
                'SeTax1', w0,
                'CdTax1', w0,
                'PerTax1', w1,
                'SeTax2', w0,
                'CdTax2', w0,
                'PerTax2', w1,
                'SeTax3', w0,
                'CdTax3', w0,
                'PerTax3', w1,
                'SeTaxVat', w0,
                'CdTaxVat', w0,
                'SeTaxImport', w0,
                'CdTaxImport', w0,
                'SeTaxExport', w0,
                'CdTaxExport', w0,
                'SeTaxSpecial', w0,
                'CdTaxSpecial', w0,
                'SeAccMaterial', w0,
                'CdAccMaterial', w0,
                'SeAccSales', w0,
                'CdAccSales', w0,
                'SeAccIntSales', w0,
                'CdAccIntSales', w0,
                'SeAccCogs', w0,
                'CdAccCogs', w0,
                'SeAccReturn', w0,
                'CdAccReturn', w0,
                'SeAccDiscount', w0,
                'CdAccDiscount', w0,
                'SeAccWip', w0,
                'CdAccWip', w0,
                'DateInsert', w0,
                'DateUpdate', w0,
                'InchargeInsert', w0,
                'InchargeUpdate', w0,
                'InchargeComplete', w0,
                'InchargeCancel', w0,
                'InchargeApproved', w0,
                'InchargePending1', w0,
                'InchargePending2', w0,
                'CheckUse', w2,
                'DateActive', w0,
                'DateDeactive', w0,
                'CheckActive', w0,
                'DateComplete', w0,
                'DateApproved', w0,
                'DateCancel', w0,
                'DatePending1', w0,
                'DatePending2', w0,
                'CheckSync', w0,
                'MaterialFullName', w0,
                'MaterialOldName', w0,
                'Remark', w0,
                'SeSite', w0,
                'CdSite', w0
            ]);
        }
    }
}