import { fieldsProxy } from "@serenity-is/corelib";

export interface Pfk7106Row {
    ShoesCode?: string;
    ShoesCodeBase?: string;
    Customercode?: string;
    BackColor?: string;
    CustSpecNo?: string;
    ProductCode?: string;
    Style?: string;
    Article?: string;
    Line?: string;
    Mcode?: string;
    ColorCode?: string;
    McodeName?: string;
    ColorName?: string;
    VerAll?: string;
    VerSam?: string;
    VerBom?: string;
    VerCbd?: string;
    VerRot?: string;
    VerJob?: string;
    CustSpecNo1?: string;
    SeProductType?: string;
    CdProductType?: string;
    SeProductSize?: string;
    CdProductSize?: string;
    SeSpecState?: string;
    CdSpecState?: string;
    Szno?: string;
    SpeciticSize?: string;
    SeSeason?: string;
    CdSeason?: string;
    SeGender?: string;
    CdGender?: string;
    LastCode?: string;
    LastWidth?: string;
    LastQty?: number;
    MoldCode?: string;
    MoldSpec?: string;
    MoldQty?: number;
    QtyAverage?: number;
    QtyAverage1?: number;
    QtyAverage2?: number;
    QtyAverage3?: number;
    CuttingDieCode?: string;
    TexonCode?: string;
    TexonColor?: string;
    InsoleCode?: string;
    InsoleColor?: string;
    OutsoleCode?: string;
    OutsoleColor?: string;
    OutsoleColorCode?: string;
    MidSoleCode?: string;
    MidsoleColor?: string;
    LogoCode?: string;
    LogoColor?: string;
    LogoColorCode?: string;
    SizeRange?: string;
    Note0?: string;
    Note1?: string;
    Note2?: string;
    Note3?: string;
    Note4?: string;
    Note5?: string;
    Note6?: string;
    Note7?: string;
    Note8?: string;
    Note9?: string;
    Note10?: string;
    DateExchangePrice?: string;
    ExchangePrice?: number;
    PriceUsd?: number;
    PriceVnd?: number;
    DateLable1?: string;
    DateLable2?: string;
    DateLable3?: string;
    DateInsert?: string;
    DateUpdate?: string;
    InchargeDesigner?: string;
    InchargeStep1?: string;
    InchargeStep2?: string;
    InchargeStep3?: string;
    InchargeInsert?: string;
    InchargeUpdate?: string;
    InchargeCbdI?: string;
    InchargeCbdU?: string;
    InchargeBomI?: string;
    InchargeBomU?: string;
    InchargeConI?: string;
    InchargeConU?: string;
    CheckParent?: string;
    ShoesParent?: string;
    CheckUse?: string;
    TimeInsert?: string;
    TimeUpdate?: string;
    CheckComplete?: string;
    InchargeComplete?: string;
    DateComplete?: string;
    InchargeCompleteUn?: string;
    DateCompleteUn?: string;
    TimeComplete?: string;
    CheckBom?: string;
    InchargeBomCom?: string;
    DateBomCom?: string;
    InchargeBomUn?: string;
    DateBomUn?: string;
    TimeBomCom?: string;
    CheckCbd?: string;
    InchargeCbdCom?: string;
    DateCbdCom?: string;
    InchargeCbdUn?: string;
    DateCbdUn?: string;
    TimeCbdCom?: string;
    CheckCon?: string;
    InchargeConCom?: string;
    DateConCom?: string;
    InchargeConUn?: string;
    DateConUn?: string;
    TimeConCom?: string;
    CheckFb?: string;
    CheckSameMold?: string;
    Remark?: string;
    SeSite?: string;
    CdSite?: string;
}

export abstract class Pfk7106Row {
    static readonly idProperty = 'ShoesCode';
    static readonly nameProperty = 'ShoesCode';
    static readonly localTextPrefix = 'Default.Pfk7106';
    static readonly deletePermission = 'Administration:General';
    static readonly insertPermission = 'Administration:General';
    static readonly readPermission = 'Administration:General';
    static readonly updatePermission = 'Administration:General';

    static readonly Fields = fieldsProxy<Pfk7106Row>();
}