import { StringEditor, DecimalEditor, PrefixedContext, initFormType } from "@serenity-is/corelib";

export interface Pfk7106Form {
    ShoesCodeBase: StringEditor;
    Customercode: StringEditor;
    BackColor: StringEditor;
    CustSpecNo: StringEditor;
    ProductCode: StringEditor;
    Style: StringEditor;
    Article: StringEditor;
    Line: StringEditor;
    Mcode: StringEditor;
    ColorCode: StringEditor;
    McodeName: StringEditor;
    ColorName: StringEditor;
    VerAll: StringEditor;
    VerSam: StringEditor;
    VerBom: StringEditor;
    VerCbd: StringEditor;
    VerRot: StringEditor;
    VerJob: StringEditor;
    CustSpecNo1: StringEditor;
    SeProductType: StringEditor;
    CdProductType: StringEditor;
    SeProductSize: StringEditor;
    CdProductSize: StringEditor;
    SeSpecState: StringEditor;
    CdSpecState: StringEditor;
    Szno: StringEditor;
    SpeciticSize: StringEditor;
    SeSeason: StringEditor;
    CdSeason: StringEditor;
    SeGender: StringEditor;
    CdGender: StringEditor;
    LastCode: StringEditor;
    LastWidth: StringEditor;
    LastQty: DecimalEditor;
    MoldCode: StringEditor;
    MoldSpec: StringEditor;
    MoldQty: DecimalEditor;
    QtyAverage: DecimalEditor;
    QtyAverage1: DecimalEditor;
    QtyAverage2: DecimalEditor;
    QtyAverage3: DecimalEditor;
    CuttingDieCode: StringEditor;
    TexonCode: StringEditor;
    TexonColor: StringEditor;
    InsoleCode: StringEditor;
    InsoleColor: StringEditor;
    OutsoleCode: StringEditor;
    OutsoleColor: StringEditor;
    OutsoleColorCode: StringEditor;
    MidSoleCode: StringEditor;
    MidsoleColor: StringEditor;
    LogoCode: StringEditor;
    LogoColor: StringEditor;
    LogoColorCode: StringEditor;
    SizeRange: StringEditor;
    Note0: StringEditor;
    Note1: StringEditor;
    Note2: StringEditor;
    Note3: StringEditor;
    Note4: StringEditor;
    Note5: StringEditor;
    Note6: StringEditor;
    Note7: StringEditor;
    Note8: StringEditor;
    Note9: StringEditor;
    Note10: StringEditor;
    DateExchangePrice: StringEditor;
    ExchangePrice: DecimalEditor;
    PriceUsd: DecimalEditor;
    PriceVnd: DecimalEditor;
    DateLable1: StringEditor;
    DateLable2: StringEditor;
    DateLable3: StringEditor;
    DateInsert: StringEditor;
    DateUpdate: StringEditor;
    InchargeDesigner: StringEditor;
    InchargeStep1: StringEditor;
    InchargeStep2: StringEditor;
    InchargeStep3: StringEditor;
    InchargeInsert: StringEditor;
    InchargeUpdate: StringEditor;
    InchargeCbdI: StringEditor;
    InchargeCbdU: StringEditor;
    InchargeBomI: StringEditor;
    InchargeBomU: StringEditor;
    InchargeConI: StringEditor;
    InchargeConU: StringEditor;
    CheckParent: StringEditor;
    ShoesParent: StringEditor;
    CheckUse: StringEditor;
    TimeInsert: StringEditor;
    TimeUpdate: StringEditor;
    CheckComplete: StringEditor;
    InchargeComplete: StringEditor;
    DateComplete: StringEditor;
    InchargeCompleteUn: StringEditor;
    DateCompleteUn: StringEditor;
    TimeComplete: StringEditor;
    CheckBom: StringEditor;
    InchargeBomCom: StringEditor;
    DateBomCom: StringEditor;
    InchargeBomUn: StringEditor;
    DateBomUn: StringEditor;
    TimeBomCom: StringEditor;
    CheckCbd: StringEditor;
    InchargeCbdCom: StringEditor;
    DateCbdCom: StringEditor;
    InchargeCbdUn: StringEditor;
    DateCbdUn: StringEditor;
    TimeCbdCom: StringEditor;
    CheckCon: StringEditor;
    InchargeConCom: StringEditor;
    DateConCom: StringEditor;
    InchargeConUn: StringEditor;
    DateConUn: StringEditor;
    TimeConCom: StringEditor;
    CheckFb: StringEditor;
    CheckSameMold: StringEditor;
    Remark: StringEditor;
    SeSite: StringEditor;
    CdSite: StringEditor;
}

export class Pfk7106Form extends PrefixedContext {
    static readonly formKey = 'Default.Pfk7106';
    private static init: boolean;

    constructor(prefix: string) {
        super(prefix);

        if (!Pfk7106Form.init)  {
            Pfk7106Form.init = true;

            var w0 = StringEditor;
            var w1 = DecimalEditor;

            initFormType(Pfk7106Form, [
                'ShoesCodeBase', w0,
                'Customercode', w0,
                'BackColor', w0,
                'CustSpecNo', w0,
                'ProductCode', w0,
                'Style', w0,
                'Article', w0,
                'Line', w0,
                'Mcode', w0,
                'ColorCode', w0,
                'McodeName', w0,
                'ColorName', w0,
                'VerAll', w0,
                'VerSam', w0,
                'VerBom', w0,
                'VerCbd', w0,
                'VerRot', w0,
                'VerJob', w0,
                'CustSpecNo1', w0,
                'SeProductType', w0,
                'CdProductType', w0,
                'SeProductSize', w0,
                'CdProductSize', w0,
                'SeSpecState', w0,
                'CdSpecState', w0,
                'Szno', w0,
                'SpeciticSize', w0,
                'SeSeason', w0,
                'CdSeason', w0,
                'SeGender', w0,
                'CdGender', w0,
                'LastCode', w0,
                'LastWidth', w0,
                'LastQty', w1,
                'MoldCode', w0,
                'MoldSpec', w0,
                'MoldQty', w1,
                'QtyAverage', w1,
                'QtyAverage1', w1,
                'QtyAverage2', w1,
                'QtyAverage3', w1,
                'CuttingDieCode', w0,
                'TexonCode', w0,
                'TexonColor', w0,
                'InsoleCode', w0,
                'InsoleColor', w0,
                'OutsoleCode', w0,
                'OutsoleColor', w0,
                'OutsoleColorCode', w0,
                'MidSoleCode', w0,
                'MidsoleColor', w0,
                'LogoCode', w0,
                'LogoColor', w0,
                'LogoColorCode', w0,
                'SizeRange', w0,
                'Note0', w0,
                'Note1', w0,
                'Note2', w0,
                'Note3', w0,
                'Note4', w0,
                'Note5', w0,
                'Note6', w0,
                'Note7', w0,
                'Note8', w0,
                'Note9', w0,
                'Note10', w0,
                'DateExchangePrice', w0,
                'ExchangePrice', w1,
                'PriceUsd', w1,
                'PriceVnd', w1,
                'DateLable1', w0,
                'DateLable2', w0,
                'DateLable3', w0,
                'DateInsert', w0,
                'DateUpdate', w0,
                'InchargeDesigner', w0,
                'InchargeStep1', w0,
                'InchargeStep2', w0,
                'InchargeStep3', w0,
                'InchargeInsert', w0,
                'InchargeUpdate', w0,
                'InchargeCbdI', w0,
                'InchargeCbdU', w0,
                'InchargeBomI', w0,
                'InchargeBomU', w0,
                'InchargeConI', w0,
                'InchargeConU', w0,
                'CheckParent', w0,
                'ShoesParent', w0,
                'CheckUse', w0,
                'TimeInsert', w0,
                'TimeUpdate', w0,
                'CheckComplete', w0,
                'InchargeComplete', w0,
                'DateComplete', w0,
                'InchargeCompleteUn', w0,
                'DateCompleteUn', w0,
                'TimeComplete', w0,
                'CheckBom', w0,
                'InchargeBomCom', w0,
                'DateBomCom', w0,
                'InchargeBomUn', w0,
                'DateBomUn', w0,
                'TimeBomCom', w0,
                'CheckCbd', w0,
                'InchargeCbdCom', w0,
                'DateCbdCom', w0,
                'InchargeCbdUn', w0,
                'DateCbdUn', w0,
                'TimeCbdCom', w0,
                'CheckCon', w0,
                'InchargeConCom', w0,
                'DateConCom', w0,
                'InchargeConUn', w0,
                'DateConUn', w0,
                'TimeConCom', w0,
                'CheckFb', w0,
                'CheckSameMold', w0,
                'Remark', w0,
                'SeSite', w0,
                'CdSite', w0
            ]);
        }
    }
}