import { fieldsProxy } from "@serenity-is/corelib";

export interface Pfk7101Row {
    CustomerCode?: string;
    QrCode?: number[];
    ACodeReceivable?: string;
    ACodePayable?: string;
    DevelopmentCode?: string;
    QrCodeName?: string;
    QrCodeTel?: string;
    CustomerName?: string;
    CustomerName1?: string;
    CustomerNameSimply?: string;
    CustomerNameSimply1?: string;
    FaceId?: string;
    SePassWord?: string;
    CdPassWord?: string;
    SeDeliveryTerm?: string;
    CdDeliveryTerm?: string;
    SePaymentTerm?: string;
    CdPaymentTerm?: string;
    SePaymentCondition?: string;
    CdPaymentCondition?: string;
    SePaymentDay?: string;
    CdPaymentDay?: string;
    SePaymentTime?: string;
    CdPaymentTime?: string;
    SeSite?: string;
    CdSite?: string;
    SeTeam?: string;
    CdTeam?: string;
    ForeignName1?: string;
    ForeignName2?: string;
    CompanyId?: string;
    CompanyType?: string;
    CompanyItem?: string;
    Representative?: string;
    AddressNo?: string;
    Address1?: string;
    Address2?: string;
    Destination?: string;
    FinalShop?: string;
    Country?: string;
    InvoiceAccount?: string;
    TaxExempt?: string;
    SeSupplierGroup?: string;
    CdSupplierGroup?: string;
    SePoGroup?: string;
    CdPoGroup?: string;
    SeSoGroup?: string;
    CdSoGroup?: string;
    TelephoneCompany?: string;
    TelephoneHand?: string;
    FaxNo?: string;
    Email?: string;
    BeneficiaryName?: string;
    AccountNumber?: string;
    BankName?: string;
    BankAddress?: string;
    SwiftCode?: string;
    CdFactory?: string;
    CheckKindCustomer?: string;
    SeCancelDate?: string;
    CdCancelDate?: string;
    SeCustomerDivision?: string;
    CdCustomerDivision?: string;
    SeCustomerLocation?: string;
    CdCustomerLocation?: string;
    SeTaxGroup?: string;
    CdTaxGroup?: string;
    InCharge?: string;
    InChargeSale?: string;
    CheckTax?: string;
    CheckCustomer?: string;
    CheckSupplier?: string;
    CheckEmployee?: string;
    CheckInside?: string;
    CheckOutside?: string;
    CheckOthers?: string;
    CheckUse?: string;
    InchargeInsert?: string;
    InchargeUpdate?: string;
    DateInsert?: string;
    DateUpdate?: string;
    TimeInsert?: string;
    TimeUpdate?: string;
    TimeLast?: string;
    DateActive?: string;
    DateDeactive?: string;
    CheckActive?: string;
    ParaNo1?: number;
    ParaNo2?: number;
    ParaNo3?: number;
    CheckSync?: string;
    CheckCustomerStatus?: string;
    DateComplete?: string;
    DateApproved?: string;
    DateCancel?: string;
    DatePending1?: string;
    DatePending2?: string;
    Remark?: string;
    CheckOption1?: string;
    CheckOption2?: string;
    CheckOption3?: string;
    CheckOption4?: string;
    CheckOption5?: string;
    CheckOption6?: string;
    CheckOption7?: string;
    CheckOption8?: string;
    CheckOption9?: string;
    CheckOption10?: string;
    Shipper?: string;
    ShipperTo?: string;
    Buyer?: string;
    Consignee?: string;
    LcNo?: string;
    DateLc?: string;
    Notifyparty?: string;
    NotifypartyAnd?: string;
    VisAllName?: string;
    DateDepart?: string;
    FlightNo?: string;
    ShipFrom?: string;
    ShipTo?: string;
    ShipMark?: string;
    Remarks?: string;
    TermPri?: string;
    Shipper1?: string;
    ShipperTo1?: string;
    Buyer1?: string;
    Consignee1?: string;
    LcNo1?: string;
    DateLc1?: string;
    Notifyparty1?: string;
    NotifypartyAnd1?: string;
    VisAllName1?: string;
    DateDepart1?: string;
    FlightNo1?: string;
    ShipFrom1?: string;
    ShipTo1?: string;
    ShipMark1?: string;
    Remarks1?: string;
    TermPri1?: string;
}

export abstract class Pfk7101Row {
    static readonly idProperty = 'CustomerCode';
    static readonly nameProperty = 'CustomerCode';
    static readonly localTextPrefix = 'Default.Pfk7101';
    static readonly deletePermission = 'Administration:General';
    static readonly insertPermission = 'Administration:General';
    static readonly readPermission = 'Administration:General';
    static readonly updatePermission = 'Administration:General';

    static readonly Fields = fieldsProxy<Pfk7101Row>();
}